# Generated by Django 5.1.1 on 2024-11-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
