# Generated by Django 5.1.1 on 2024-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_quizquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
