# Generated by Django 5.1.1 on 2025-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_quizquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
            preserve_default=False,
        ),
    ]
