# Generated by Django 5.2 on 2025-04-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('family', 'Family'), ('career', 'Career'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='prayed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
